apiVersion: v1
kind: Pod
metadata:
  name: fresco-nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      name: SERVER_URL_ENV
      valueFrom:
        configMapKeyRef:
          name: fresco-config
          key: SERVER_URL
    volumeMounts:
    - name: fresco-secret
      mountPath: "/etc/test"
      readOnly: true
    - name: fresco-pvc
      mountPath: "/usr/share/nginx/html"
  volumes:
    - name: fresco-secret
      secret:
        secretName: fresco-secret
    - name: fresco-pvc
      persistentVolumeClaim:
        claimName: fresco-pvc

